---
title: Kids Ruby Quiz
hero_image: images/banner.png
description: Make your own quiz game with Kids Ruby and your Raspberry Pi
original_url: https://raspberrypi.org/learning/kids-ruby-quiz
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: raspberry-pi
site_areas: projects
hardware: raspberry-pi
software: ''
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Kids Ruby Quiz
- title: Creating the sequence
- title: Introduction, welcoming the player
- title: Asking questions and working with user input
- title: Adding more questions
- title: Game over and final score
- title: What next?